[project]
name = "jupyter-local-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "WangYoudian", email = "bruce.y.d.wang@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datalayer-pycrdt==0.12.17",
    "jupyter-ai-agents>=1.0.2",
    "jupyterlab>=4.2,<5",
]

[project.scripts]
jupyter-local-dev = "jupyter_local_dev:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
